name: assistantapps_flutter_common_example
description: Common functionality between the AssistantApps
# author: Kurt Lourens
homepage: https://assistantapps.com
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  storybook_flutter: ^0.10.1
  after_layout: 1.1.0

  # temp
  platform: ^3.1.0

  assistantapps_flutter_common:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

