name: assistantapps_flutter_common_example
description: Common functionality between the AssistantApps
# author: Kurt Lourens
homepage: https://assistantapps.com
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  storybook_flutter: 0.14.0
  after_layout: 1.2.0

  assistantapps_flutter_common:
    path: ../

  flutter:
    sdk: flutter

  file_picker: any
  file_selector_web: any
  flutter_secure_storage_web: any
  image_picker_for_web: any
  package_info_plus_web: any
  platform_device_id_web: any
  share_plus_web: any
  shared_preferences_web: any
  url_launcher_web: any
  flutter_web_plugins: any
  flutter_localizations: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

dependency_overrides:
  http: 1.1.2
  win32: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
