name: assistantapps_flutter_common
description: Common functionality between the AssistantApps
version: 0.2.62
# author: Kurt Lourens
homepage: https://assistantapps.com
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  after_layout: 1.2.0
  animate_do: 3.3.4
  animated_background: 2.0.0
  badges: 3.1.2
  bitsdojo_window: 0.1.6
  breakpoint: 1.2.0
  cached_network_image: 3.4.1
  collection: 1.19.0
  country_icons: 3.0.0
  dotted_border: 2.1.0
  dropdown_button2: 2.3.9
  enum_to_string: 2.0.1
  extended_masked_text: 3.0.1
  file_picker: 8.1.2
  flutter_chip_tags: 2.0.2
  flutter_markdown: 0.7.3+1
  flutter_secure_storage: 9.2.2
  flutter_staggered_grid_view: 0.7.0
  flutter_sticky_header: 0.6.5
  flutter_svg: 2.0.10+1
  get_it: 7.7.0
  group_button: 5.3.4
  http: 1.2.2
  image_painter: 0.7.1
  image_picker: 1.1.2
  intl: 0.19.0
  material_segmented_control: 5.0.1
  octo_image: 2.1.0
  package_info_plus: 8.0.2
  pagination_view: 2.0.0
  percent_indicator: 4.2.3
  photo_view: 0.15.0
  platform_device_id: 1.0.1
  responsive_grid: 2.4.4
  screenshot: 3.0.0
  share_plus: 10.0.2
  shared_preferences: 2.3.2
  shimmer: 3.0.0
  signalr_netcore: 1.3.9
  spring: 2.0.2
  sweetsheet: 0.4.0
  talker: 4.4.1
  talker_flutter: 4.4.1
  timelines: 0.1.0
  universal_platform: 1.1.0
  url_launcher: 6.3.0
  uuid: 4.5.0
  websafe_svg: 3.0.1+2

  # Time format with null safety
  time_formatter:
    git:
      url: https://github.com/Vishal-Isharani/time_formatter
      ref: master

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  collection: 1.19.0
  # http: 1.1.2
  # win32: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/infographic/
    - assets/images/guide/
    - assets/images/special/
