name: assistantapps_flutter_common
description: A new Flutter package project.
version: 0.0.6
author: Kurt Lourens
homepage: https://assistantapps.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Base
  get_it: 4.0.2
  http: 0.12.2

  # UI
  pagination_view: ^1.0.3+2
  animated_background: ^1.0.5
  timeline_tile: 0.1.2
  octo_image: ^0.3.0
  cached_network_image: ^2.5.0
  flutter_markdown: 0.4.1
  after_layout: ^1.0.7+2
  modal_bottom_sheet: ^1.0.0+1
  material_segmented_control: 2.1.0+1
  flushbar: 1.10.4
  fl_chart: ^0.12.2

  # Misc
  enum_to_string: 1.0.9
  url_launcher: 5.4.10
  package_info: 0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/donations/
    - assets/images/special/