name: assistantapps_flutter_common
description: Common functionality between the AssistantApps
version: 0.0.71
# author: Kurt Lourens
homepage: https://assistantapps.com

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  get_it: 7.2.0
  http: 0.13.4
  signalr_netcore: 1.2.3+1

  # UI
  after_layout: 1.1.0
  animate_do: 2.1.0
  animated_background: 2.0.0
  auth_buttons: 2.0.4
  badges: 2.0.2
  breakpoint: 1.2.0
  cached_network_image: 3.2.0
  enum_to_string: 2.0.1
  extended_masked_text: 2.3.1
  fl_chart: 0.41.0
  flutter_layout_grid: 1.0.3
  flutter_markdown: 0.6.9
  flutter_staggered_grid_view: 0.4.1 # Big migration
  grouped_checkbox: 1.0.0
  intl: 0.17.0
  material_segmented_control: 3.1.2
  modal_bottom_sheet: 2.0.0
  octo_image: 1.0.1
  package_info_plus: 1.3.0
  pagination_view: 2.0.0
  percent_indicator: 4.0.0
  photo_view: 0.13.0
  platform_device_id: 1.0.1
  share_plus: 3.0.4
  sweetsheet: 0.4.0
  time_formatter: 1.0.0+5
  timeline_tile: 2.0.0
  uuid: 3.0.5
  universal_platform: 1.0.0+1
  url_launcher: 6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/special/
