name: assistantapps_flutter_common
description: Common functionality between the AssistantApps
version: 0.1.98
# author: Kurt Lourens
homepage: https://assistantapps.com
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  get_it: 7.2.0
  http: 0.13.5
  signalr_netcore: 1.3.3
  shared_preferences: 2.0.15
  flutter_secure_storage: 6.0.0

  # UI
  after_layout: 1.2.0
  animate_do: 2.1.0
  animated_background: 2.0.0
  auth_buttons: 3.0.0
  badges: 2.0.3
  breakpoint: 1.2.0
  cached_network_image: 3.2.2
  country_icons: 2.0.2
  dotted_border: 2.0.0+2
  enum_to_string: 2.0.1
  extended_masked_text: 2.3.1
  file_picker: 5.2.0+1
  flutter_chip_tags: 2.0.2
  # flutter_layout_grid: 1.0.6
  flutter_markdown: 0.6.12
  flutter_staggered_grid_view: 0.6.2
  flutter_sticky_header: 0.6.4
  flutter_svg: 1.1.5
  group_button: 5.2.2
  image_picker: 0.8.6
  intl: 0.17.0
  material_segmented_control: 4.0.0
  modal_bottom_sheet: 2.1.2
  octo_image: 1.0.2
  package_info_plus: 1.4.3+1
  pagination_view: 2.0.0
  percent_indicator: 4.2.2
  photo_view: 0.14.0
  platform_device_id: 1.0.1
  responsive_grid: 2.1.0
  share_plus: 4.4.0
  shimmer: 2.0.0
  spring: 2.0.2
  sweetsheet: 0.4.0
  timelines: 0.1.0
  uuid: 3.0.6
  universal_platform: 1.0.0+1
  url_launcher: 6.1.6
  websafe_svg: 2.1.2+4

  # Time format with null safety
  time_formatter:
    git:
      url: https://github.com/Vishal-Isharani/time_formatter
      ref: master

  # logging
  talker: 2.0.0+1
  talker_flutter: ^2.0.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: 2.0.1
  storybook_flutter: 0.11.2

# dependency_overrides:
#   ffi: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/infographic/
    - assets/images/guide/
    - assets/images/special/
