name: assistantapps_flutter_common
description: Common functionality between the AssistantApps
version: 0.1.45
# author: Kurt Lourens
homepage: https://assistantapps.com
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  get_it: 7.2.0
  http: 0.13.4
  signalr_netcore: 1.2.5
  collection: 1.15.0
  shared_preferences: 2.0.13
  flutter_secure_storage: 5.0.2

  # UI
  after_layout: 1.1.0
  animate_do: 2.1.0
  animated_background: 2.0.0
  auth_buttons: 2.0.4
  badges: 2.0.2
  breakpoint: 1.2.0
  cached_network_image: 3.2.0
  dotted_border: 2.0.0+2
  enum_to_string: 2.0.1
  extended_masked_text: 2.3.1
  file_picker_cross: 4.5.0
  fl_chart: 0.45.1
  flutter_chip_tags: 1.0.4
  flutter_layout_grid: 1.0.6
  flutter_markdown: 0.6.10
  flutter_staggered_grid_view: 0.4.1 # Big migration
  flutter_sticky_header: 0.6.1
  flutter_svg: 1.0.3
  giffy_dialog: 1.8.0
  group_button: 5.0.1
  image_picker: 0.8.5
  intl: 0.17.0
  material_segmented_control: 3.1.2
  modal_bottom_sheet: 2.0.0
  octo_image: 1.0.1
  package_info_plus: 1.4.2
  pagination_view: 2.0.0
  percent_indicator: 4.0.0
  photo_view: 0.13.0
  platform_device_id: 1.0.1
  responsive_grid: 2.0.0
  share_plus: 4.0.4
  shimmer: 2.0.0
  spring: 2.0.2
  sweetsheet: 0.4.0
  timelines: 0.1.0
  uuid: 3.0.6
  universal_platform: 1.0.0+1
  url_launcher: 6.0.20
  websafe_svg: 2.1.1

  # Time format with null safety
  time_formatter:
    git:
      url: https://github.com/Vishal-Isharani/time_formatter
      ref: master

  # logging
  talker: 0.11.0
  talker_flutter:
    git:
      url: https://github.com/AssistantApps/talker.git
      ref: master
      path: packages/talker_flutter/

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^1.0.0
  storybook_flutter: ^0.10.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/infographic/
    - assets/images/guide/
    - assets/images/special/
