name: assistantapps_flutter_common
description: A new Flutter package project.
version: 0.0.23
author: Kurt Lourens
homepage: https://assistantapps.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Base
  get_it: 6.1.1
  http: 0.13.2

  # UI
  after_layout: 1.1.0
  animated_background: 1.0.5
  another_flushbar: 1.10.20
  auth_buttons: 1.0.1
  badges: 2.0.0-nullsafety.1
  breakpoint: 1.2.0
  cached_network_image: 3.0.0
  entry: 0.0.2+2
  enum_to_string: 2.0.1
  extended_masked_text: 2.1.0
  fl_chart: 0.35.0
  flutter_layout_grid: 1.0.1
  flutter_markdown: 0.6.1
  flutter_staggered_grid_view: 0.4.0
  grouped_checkbox: 1.0.0
  intl: 0.17.0
  material_segmented_control: 3.1.2
  modal_bottom_sheet: 2.0.0
  octo_image: 1.0.0+1
  package_info_plus: 1.0.1
  pagination_view: 2.0.0-nullsafety.0
  percent_indicator: 3.0.1
  photo_view: 0.11.1
  time_formatter: 1.0.0+5
  timeline_tile: 2.0.0
  universal_platform: 1.0.0-nullsafety
  url_launcher: 6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/special/