name: assistantapps_flutter_common
description: A new Flutter package project.
version: 0.0.37
author: Kurt Lourens
homepage: https://assistantapps.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Base
  get_it: 6.1.1
  http: 0.13.2
  signalr_netcore: 1.0.1

  # UI
  after_layout: 1.1.0
  animate_do: 2.0.0
  animated_background: 2.0.0
  another_flushbar: 1.10.22
  auth_buttons: 1.0.1+3
  badges: 2.0.1
  breakpoint: 1.2.0
  cached_network_image: 3.0.0
  enum_to_string: 2.0.1
  extended_masked_text: 2.2.0
  fl_chart: 0.36.1
  flutter_layout_grid: 1.0.1
  flutter_markdown: 0.6.2
  flutter_staggered_grid_view: 0.4.0
  grouped_checkbox: 1.0.0
  intl: 0.17.0
  material_segmented_control: 3.1.2
  modal_bottom_sheet: 2.0.0
  octo_image: 1.0.0+1
  package_info_plus: 1.0.1
  pagination_view: 2.0.0-nullsafety.0
  percent_indicator: 3.0.1
  photo_view:
    git:
      url: git://github.com/fireslime/photo_view
      ref: 52685ab7beaf8a9107904bdb8a1590924015d016

  platform_device_id: 1.0.1
  time_formatter: 1.0.0+5
  timeline_tile: 2.0.0
  uuid: ^3.0.4
  universal_platform: 1.0.0-nullsafety
  url_launcher: 6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/special/