name: assistantapps_flutter_common
description: A new Flutter package project.
version: 0.0.12
author: Kurt Lourens
homepage: https://assistantapps.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Base
  get_it: ^5.0.6
  http: 0.12.2

  # UI
  pagination_view: ^1.0.4
  animated_background: ^1.0.5
  timeline_tile: 1.0.0
  octo_image: ^0.3.0
  cached_network_image: ^2.5.0
  flutter_markdown: 0.5.2
  after_layout: ^1.0.7+2
  modal_bottom_sheet: ^1.0.0+1
  material_segmented_control: 2.1.1+1
  flushbar: 1.10.4
  fl_chart: ^0.12.2
  percent_indicator: 2.1.9+1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.2
  flutter_layout_grid: ^0.11.3

  # Misc
  enum_to_string: 1.0.14
  url_launcher: ^5.7.10
  package_info: 0.4.3+4
  universal_platform: ^0.1.3
  breakpoint: ^1.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/special/