name: assistantapps_flutter_common
description: A new Flutter package project.
version: 0.0.21
author: Kurt Lourens
homepage: https://assistantapps.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Base
  get_it: 6.1.1
  http: 0.13.2

  # UI
  pagination_view: 2.0.0-nullsafety.0
  animated_background: 1.0.5
  timeline_tile: 2.0.0
  octo_image: 1.0.0+1
  cached_network_image: 3.0.0
  flutter_markdown: 0.6.1
  after_layout: 1.1.0
  modal_bottom_sheet: 2.0.0
  material_segmented_control: 3.1.2
  another_flushbar: 1.10.20
  fl_chart: 0.35.0
  percent_indicator: 3.0.1
  flutter_staggered_grid_view: 0.4.0
  flutter_layout_grid: 1.0.1
  time_formatter: 1.0.0+5
  entry: 0.0.2+2

  # Misc
  intl: 0.17.0
  enum_to_string: 2.0.1
  url_launcher: 6.0.3
  package_info_plus: 1.0.1
  universal_platform: 1.0.0-nullsafety
  breakpoint: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/special/