name: assistantapps_flutter_common
description: Common functionality between the AssistantApps
version: 0.2.48
# author: Kurt Lourens
homepage: https://assistantapps.com
publish_to: none

environment:
  sdk: '>=3.0.0-276.0.dev <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  get_it: 7.6.0
  http: 0.13.6
  signalr_netcore: 1.3.6
  shared_preferences: 2.2.1
  flutter_secure_storage: 8.1.0

  # UI
  after_layout: 1.2.0
  animate_do: 3.0.2
  animated_background: 2.0.0
  badges: 3.1.2
  bitsdojo_window: 0.1.5
  breakpoint: 1.2.0
  cached_network_image: 3.3.0
  collection: 1.18.0
  country_icons: 2.0.2
  dotted_border: 2.0.0+3
  dropdown_button2: 2.3.9
  enum_to_string: 2.0.1
  extended_masked_text: 2.3.1
  file_picker: 5.2.10
  flutter_chip_tags: 2.0.2
  # flutter_layout_grid: 1.0.6
  flutter_markdown: 0.6.15
  image_painter: 0.6.0
  flutter_staggered_grid_view: 0.7.0
  flutter_sticky_header: 0.6.5
  flutter_svg: 2.0.7
  group_button: 5.3.3
  image_picker: 1.0.4
  intl: 0.18.1
  material_segmented_control: 5.0.0
  octo_image: 2.0.0
  package_info_plus: 3.1.2
  pagination_view: 2.0.0
  path: 1.8.3
  percent_indicator: 4.2.3
  photo_view: 0.14.0
  platform_device_id: 1.0.1
  responsive_grid: 2.4.4
  # screenshot: 1.3.0
  share_plus: 6.3.4
  shimmer: 3.0.0
  spring: 2.0.2
  sweetsheet: 0.4.0
  timelines: 0.1.0
  uuid: 3.0.7
  universal_platform: 1.0.0+1
  url_launcher: 6.1.11
  websafe_svg: 3.0.0+5

  # Time format with null safety
  time_formatter:
    git:
      url: https://github.com/Vishal-Isharani/time_formatter
      ref: master

  # Screenshot package with a fix for Flutter master channel
  screenshot:
    git:
      url: https://github.com/AssistantApps/screenshot
      ref: master

  # logging
  talker: 2.4.1
  talker_flutter: 2.4.3

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: 2.0.3

# dependency_overrides:
#   collection: 1.17.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/infographic/
    - assets/images/guide/
    - assets/images/special/
