name: assistantapps_flutter_common
description: Common functionality between the AssistantApps
version: 0.2.32
# author: Kurt Lourens
homepage: https://assistantapps.com
publish_to: none

environment:
  sdk: '>=3.0.0-276.0.dev <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  get_it: 7.2.0
  http: 0.13.5
  signalr_netcore: 1.3.3
  shared_preferences: 2.0.17
  flutter_secure_storage: 7.0.1

  # UI
  after_layout: 1.2.0
  animate_do: 3.0.2
  animated_background: 2.0.0
  auth_buttons: 3.0.0
  badges: 3.0.2
  bitsdojo_window: 0.1.5
  breakpoint: 1.2.0
  cached_network_image: 3.2.3
  collection: 1.17.1
  country_icons: 2.0.2
  dotted_border: 2.0.0+3
  dropdown_button2: 2.0.0
  enum_to_string: 2.0.1
  extended_masked_text: 2.3.1
  file_picker: 5.2.5
  flutter_chip_tags: 2.0.2
  # flutter_layout_grid: 1.0.6
  flutter_markdown: 0.6.14
  image_painter: 0.5.0
  flutter_staggered_grid_view: 0.6.2
  flutter_sticky_header: 0.6.5
  flutter_svg: 1.1.6
  group_button: 5.2.2
  image_picker: 0.8.6+4
  intl: 0.18.0
  material_segmented_control: 4.2.0
  modal_bottom_sheet: ^3.0.0-pre
  octo_image: 1.0.2
  package_info_plus: 3.0.3
  pagination_view: 2.0.0
  path: 1.8.3
  percent_indicator: 4.2.3
  photo_view: 0.14.0
  platform_device_id: 1.0.1
  responsive_grid: 2.1.0
  screenshot: 1.3.0
  share_plus: 6.3.1
  shimmer: 2.0.0
  spring: 2.0.2
  sweetsheet: 0.4.0
  timelines: 0.1.0
  uuid: 3.0.7
  universal_platform: 1.0.0+1
  url_launcher: 6.1.10
  websafe_svg: 2.1.3+1

  # Time format with null safety
  time_formatter:
    git:
      url: https://github.com/Vishal-Isharani/time_formatter
      ref: master

  # logging
  talker: 2.4.0
  talker_flutter: 2.4.3

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: 2.0.1
  storybook_flutter: 0.11.4

# dependency_overrides:
#   ffi: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    #
    - assets/images/
    - assets/images/donations/
    - assets/images/icon/
    - assets/images/infographic/
    - assets/images/guide/
    - assets/images/special/
